#VERSION=0.2
#TYPE=script
name: CI

on: push

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - run: python -m pip install pipenv pylint

      - run: pipenv run pylint **/*.py

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
